apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deploy-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-deploy-demo
  template:
    metadata:
      labels:
        app: go-deploy-demo
    spec:
      containers:
        - name: go-deploy-demo
          image: org/go-deploy-demo:latest
          ports:
            - containerPort: 8090
          env:
            - name: ENV
              value: "prod"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5